dist: bionic
language: python
python:
  - "3.7"
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true
install:
  - cd api && pip install -r requirements.txt && cd ..
  - cd client && yarn install && cd ..
script:
  - TESTING=true pytest api
  - cd client && yarn build && cd ..
